ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
tasks:
    - command: >
        npm i vercel -g && brew install node@14 && brew unlink node && brew link node@14 && npm install && npm run start
